//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace InstaScrump.Database.Model
{
	/// <summary>
	/// Database       : InstaScrump
	/// Data Source    : InstaScrump
	/// Server Version : 3.24.0
	/// </summary>
	public partial class InstaScrumpDB : LinqToDB.Data.DataConnection
	{
		public ITable<Follow>     Follows   { get { return this.GetTable<Follow>(); } }
		public ITable<LoginData>  LoginData { get { return this.GetTable<LoginData>(); } }
		public ITable<UserMedium> UserMedia { get { return this.GetTable<UserMedium>(); } }

		public InstaScrumpDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public InstaScrumpDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table("Follow")]
	public partial class Follow
	{
		[Column("_id", DataType=DataType.Int64,    Length=8, Precision=19, Scale=0), PrimaryKey, Identity]
		public long Id { get; set; } // integer

		[Column(       DataType=DataType.Text,     Length=int.MaxValue, Precision=0, Scale=0), NotNull]
		public string Username { get; set; } // text(max)

		[Column(       DataType=DataType.Int64,    Length=8, Precision=19, Scale=0), NotNull]
		public long InstaPk { get; set; } // integer

		[Column(       DataType=DataType.Text,     Length=int.MaxValue, Precision=0, Scale=0), NotNull]
		public string FullName { get; set; } // text(max)

		[Column(       DataType=DataType.Boolean,  Length=1, Precision=0, Scale=0), NotNull]
		public bool Favorit { get; set; } // boolean

		[Column(       DataType=DataType.DateTime, Length=8, Precision=0, Scale=0),    Nullable]
		public DateTime? LastUpdate { get; set; } // datetime
	}

	[Table("LoginData")]
	public partial class LoginData
	{
		[Column("_id", DataType=DataType.Int64, Length=8, Precision=19, Scale=0), PrimaryKey, Identity]
		public long Id { get; set; } // integer

		[Column(       DataType=DataType.Text,  Length=int.MaxValue, Precision=0, Scale=0), NotNull]
		public string UserName { get; set; } // text(max)

		[Column(       DataType=DataType.Text,  Length=int.MaxValue, Precision=0, Scale=0), NotNull]
		public string UserPswd { get; set; } // text(max)

		[Column(       DataType=DataType.Text,  Length=int.MaxValue, Precision=0, Scale=0), NotNull]
		public string Salt { get; set; } // text(max)
	}

	[Table("UserMedia")]
	public partial class UserMedium
	{
		[Column("_id", DataType=DataType.Int64, Length=8, Precision=19, Scale=0), PrimaryKey, Identity]
		public long Id { get; set; } // integer

		[Column(       DataType=DataType.Text,  Length=int.MaxValue, Precision=0, Scale=0), NotNull]
		public string MediaId { get; set; } // text(max)

		[Column(       DataType=DataType.Int16, Length=2, Precision=5, Scale=0), NotNull]
		public InstaScrump.Common.Enums.MediaTyp MediaTyp { get; set; } // smallint

		[Column(       DataType=DataType.Int64, Length=8, Precision=19, Scale=0), NotNull]
		public long InstaPk { get; set; } // integer
	}

	public static partial class TableExtensions
	{
		public static Follow Find(this ITable<Follow> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static LoginData Find(this ITable<LoginData> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static UserMedium Find(this ITable<UserMedium> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		#region Associations

		#region UserMedium Associations

		/// <summary>
		/// FK_UserMedia_0_0
		/// </summary>
		[Association(ThisKey="InstaPk", OtherKey="InstaPk", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_UserMedia_0_0")]
		public static IQueryable<Follow> Follows(this UserMedium obj, IDataContext db)
		{
			return db.GetTable<Follow>().Where(c => c.InstaPk == obj.InstaPk);
		}

		/// <summary>
		/// FK_UserMedia_0_0
		/// </summary>
		[Association(ThisKey="InstaPk", OtherKey="InstaPk", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_UserMedia_0_0")]
		public static UserMedium Follow(this Follow obj, IDataContext db)
		{
			return db.GetTable<UserMedium>().Where(c => c.InstaPk == obj.InstaPk).First();
		}

		#endregion

		#endregion
	}
}

#pragma warning restore 1591
